### ISSUE TITLE
请求添加一个全局是否启用标点功能的选项

### ISSUE THREAD

**Issue by IbukiFuko** [Souma-Sumire/raidboss-user-js-public#2]
因为每次开局都会把队友头上的标点清掉，有点困扰

**Comment by Souma-Sumire** [comment]
可在邮差中禁用一切标点动作。

**Comment by IbukiFuko** [comment]
![image](https://github.com/Souma-Sumire/raidboss-user-js-public/assets/44281408/abd5e669-76dc-4c86-a0ef-48c2be2311cb)
看了日志，标点是通过command实现的，但是我自己写的一些非标点的触发器也是依赖这个的，就很尴尬

**Comment by Souma-Sumire** [comment]
那自行注释initData回调函数中的动作
