### ISSUE TITLE
Cactbot Configuration

### ISSUE THREAD

**Issue by wr123go** [Souma-Sumire/raidboss-user-js-public#6]
使用咖啡整合ACT，将config面板转换.js放置在act\Plugins\cactbot-offline\user\raidboss目录下，打开配置面板时正常打印日志，但点击 config 面板时显示空白页面。
尝试直接访问http://souma.diemoe.net/cactbot/ui/config/config.html，页面仍然为空。

**Comment by Souma-Sumire** [comment]
请按照以下步骤**一条一条的执行**
1. 确认 js 文件中的路径是 `http` 而不是 `https`
2. 无论第一条是什么，都重启ACT一次，再次尝试
3. 若还是白屏，则右键 config 页的白屏任意处，选择 `Open Devtools` ，跳转到 `Console` 面板，截图报错日志

**Comment by wr123go** [comment]
已解决，感谢
