### ISSUE TITLE
请求M4S日出的方向提示 以及食物警察功能

### ISSUE THREAD

**Issue by MistyTime** [Souma-Sumire/raidboss-user-js-public#7]
恢复成原始方法之后，日出不再播报引导激光炮的方向和塔的位置了；
还有之前的食物警察提示在更新之后被自动删除了，很需要这个检查队友的食物。

希望可以得到解决，非常感谢！

**Comment by Souma-Sumire** [comment]
> 恢复成原始方法之后，日出不再播报引导激光炮的方向和塔的位置了；

咋回事呢，我也很疑惑。

> 还有之前的食物警察提示在更新之后被自动删除了，很需要这个检查队友的食物。

加上了。之前因为感觉不太好用所以删了，因为当时做的时候为了符合NGA的规定，写的很保守。

**Comment by Souma-Sumire** [comment]
背后的真相令人暖心，之前为了转成普通js，要替换触发器ID，结果替换的时候偷懒没写正则直接用的字符串，结果改到了不该改的地方
应该于 14d1a1b3f901937813bb0dff672deafa10e80197 修正
